# ============================================================
# Lambda ARNs — put these in your .env.local
# ============================================================

output "reminder_processor_lambda_arn" {
  description = "ARN of the reminder-processor Lambda function"
  value       = aws_lambda_function.reminder_processor.arn
}

output "period_alert_lambda_arn" {
  description = "ARN of the period-alert Lambda function"
  value       = aws_lambda_function.period_alert.arn
}

output "reminder_processor_function_name" {
  description = "Name of the reminder-processor Lambda function"
  value       = aws_lambda_function.reminder_processor.function_name
}

output "period_alert_function_name" {
  description = "Name of the period-alert Lambda function"
  value       = aws_lambda_function.period_alert.function_name
}

# ============================================================
# Express App IAM Credentials — put these in your .env.local
# ============================================================

output "express_app_access_key_id" {
  description = "AWS Access Key ID for the Express app"
  value       = aws_iam_access_key.express_app.id
}

output "express_app_secret_access_key" {
  description = "AWS Secret Access Key for the Express app"
  value       = aws_iam_access_key.express_app.secret
  sensitive   = true
}

# ============================================================
# Env vars summary — copy to .env.local
# ============================================================

output "env_file_snippet" {
  description = "Copy this into your .env.local file"
  value       = <<-EOT

    # === Generated by Terraform ===
    AWS_REGION=${data.aws_region.current.name}
    AWS_ACCESS_KEY_ID=${aws_iam_access_key.express_app.id}
    AWS_SECRET_ACCESS_KEY=<run: terraform output -raw express_app_secret_access_key>
    LAMBDA_REMINDER_PROCESSOR_ARN=${aws_lambda_function.reminder_processor.arn}
    LAMBDA_PERIOD_ALERT_ARN=${aws_lambda_function.period_alert.arn}
    EVENTBRIDGE_BUS_NAME=default

  EOT
}
